version: "3"
services:

  web:
    build: ./webserver
    volumes:
      - ./webserver:/myserver
    ports:
      - "8080:8080"

  frontend:
    build: ./front
    volumes:
      - ./front:/reactApp
    ports:
      - "3000:3000"
