version: "3"
services:
  frontend:
    build: ./front
    volumes:
      - ./front/src:/reactApp/src
      - ./front/public:/reactApp/public
      - ./front/package.json:/reactApp/package.json
      - ./front/coverage:/reactApp/coverage
    ports:
      - "3000:3000"
    links:
      - webserver

  webserver:
    build: ./webserver
    volumes:
      - ./webserver/src:/myserver/src
      - ./webserver/package.json:/myserver/package.json
    ports:
      - "8080:8080"
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
