version: "3"
services:
  webserver:
    build: ./webserver
    volumes:
      - ./webserver/src:/myserver/src
    ports:
      - "8080:8080"
  frontend:
    build: ./front
    volumes:
      - ./front/src:/reactApp/src
      - ./front/public:/reactApp/public
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
